all: compile

compile: 
	gcc kulkarni_pa2_stra.c -lm -o stras
	gcc kulkarni_pa2_tro.c -lm -o tromino
	gcc kulkarni_pa2_floyd.c -lm -o floyd

run1:
	./stras
run2:
	./tromino
run3:
	./floyd
clean:
	rm -rf stras tromino floyd